"use client";

import { useState } from "react";

type View = "Dashboard" | "Tasks" | "AI Assistant" | "Planner" | "Analytics" | "Settings";
type Task = { title: string; project: string; status: string; priority: string; date: string; color: string; done?: boolean };

const navItems: { label: View; icon: string }[] = [
  { label: "Dashboard", icon: "⌂" }, { label: "Tasks", icon: "□" }, { label: "AI Assistant", icon: "✦" },
  { label: "Planner", icon: "▦" }, { label: "Analytics", icon: "◒" }, { label: "Settings", icon: "⚙" },
];
const seedTasks: Task[] = [
  { title: "Finalize Q3 product strategy", project: "Product launch", status: "In progress", priority: "High", date: "Today", color: "coral" },
  { title: "Review design system updates", project: "Brand refresh", status: "Completed", priority: "Medium", date: "Today", color: "violet", done: true },
  { title: "Prepare weekly team update", project: "Operations", status: "To do", priority: "Low", date: "Tomorrow", color: "blue" },
  { title: "Research onboarding patterns", project: "Product launch", status: "To do", priority: "Medium", date: "Aug 27", color: "green" },
];

export default function HomePage() {
  const [view, setView] = useState<View>("Dashboard");
  const [taskState, setTaskState] = useState(seedTasks);
  const [query, setQuery] = useState("");
  const [prompt, setPrompt] = useState("");
  const [thinking, setThinking] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const filteredTasks = taskState.filter((task) => task.title.toLowerCase().includes(query.toLowerCase()));
  const completeTask = (index: number) => setTaskState((current) => current.map((task, taskIndex) => taskIndex === index ? { ...task, done: !task.done, status: task.done ? "To do" : "Completed" } : task));
  const ask = () => { if (!prompt.trim()) return; setThinking(true); window.setTimeout(() => setThinking(false), 1700); };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>Plan<span className="brand-accent">AI</span></span></div><div className="workspace-switcher"><span className="workspace-dot" /> Alex&apos;s workspace <span className="chevron">⌄</span></div><div className="nav-label">Workspace</div><nav className="nav" aria-label="Main navigation">{navItems.map((item) => <button className={`nav-item ${view === item.label ? "active" : ""}`} key={item.label} onClick={() => setView(item.label)}><span className="nav-icon">{item.icon}</span><span>{item.label}</span>{item.label === "AI Assistant" && <span className="new-dot" />}</button>)}</nav><div className="sidebar-note"><span className="spark">✦</span><strong>Plan with intelligence</strong><small>Let AI turn your ideas into action.</small><button onClick={() => setView("AI Assistant")}>Open assistant <span>→</span></button></div><div className="sidebar-bottom"><div className="profile"><span className="avatar">AM</span><div><strong>Alex Morgan</strong><small>Personal workspace</small></div><span className="more">•••</span></div></div></aside>
    <main className="main"><header className="topbar"><div><div className="breadcrumb">Workspace <span>/</span> {view}</div><h1>{view === "Dashboard" ? "Good morning, Alex" : view}</h1><p className="subtitle">{view === "Dashboard" ? "Plan smarter. Get more done." : view === "AI Assistant" ? "Your thinking partner, connected to Notion." : `Stay on top of your ${view.toLowerCase()}.`}</p></div><div className="top-actions"><button className="icon-button" aria-label="Search">⌕</button><button className="icon-button notification" aria-label="Notifications">♧<i /></button><button className="primary-button" onClick={() => setShowModal(true)}>+ New task</button></div></header><div className="view-stage" key={view}>{view === "Dashboard" && <Dashboard tasks={taskState} onComplete={completeTask} onAssistant={() => setView("AI Assistant")} />} {view === "Tasks" && <TasksView tasks={filteredTasks} query={query} setQuery={setQuery} onComplete={completeTask} onNew={() => setShowModal(true)} />} {view === "AI Assistant" && <Assistant prompt={prompt} setPrompt={setPrompt} thinking={thinking} ask={ask} />} {view === "Planner" && <Planner tasks={taskState} />} {view === "Analytics" && <Analytics />} {view === "Settings" && <Settings />}</div></main>
    {showModal && <NewTaskModal onClose={() => setShowModal(false)} />}
  </div>;
}

function Stat({ label, value, change, positive }: { label: string; value: string; change: string; positive?: boolean }) { return <article className="stat-card"><div className="stat-label">{label}<span className="stat-icon">↗</span></div><div className="stat-value">{value}</div><div className={`trend ${positive ? "positive" : ""}`}><b>↑ {change}</b> from last week</div></article>; }
function TaskRow({ task, onComplete }: { task: Task; onComplete: () => void }) { return <div className="task-row"><button className={`check ${task.done ? "done" : ""}`} onClick={onComplete} aria-label={`Complete ${task.title}`}>{task.done ? "✓" : ""}</button><span className={`task-color ${task.color}`} /><div className="task-copy"><strong>{task.title}</strong><small>{task.project} <span>·</span> {task.date}</small></div><span className={`pill ${task.status.toLowerCase().replace(" ", "-")}`}>{task.status}</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></div>; }
function Activity({ icon, title, detail, time, color }: { icon: string; title: string; detail: string; time: string; color: string }) { return <div className="activity"><span className={`activity-icon ${color}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><time>{time}</time></div>; }

function Dashboard({ tasks, onComplete, onAssistant }: { tasks: Task[]; onComplete: (index: number) => void; onAssistant: () => void }) { return <><section className="stats-grid"><Stat label="Total tasks" value="48" change="12%" /><Stat label="To do" value="18" change="4%" /><Stat label="In progress" value="07" change="8%" /><Stat label="Completed" value="23" change="18%" positive /></section><section className="hero-grid"><article className="panel focus-panel"><div className="panel-heading"><div><span className="eyebrow">Your productivity</span><h2>Make today count.</h2></div><select aria-label="Time range"><option>This week</option><option>This month</option></select></div><div className="focus-number">82<span>%</span><small> weekly momentum <b>↑ 6.4%</b></small></div><div className="line-chart"><svg viewBox="0 0 700 150" preserveAspectRatio="none"><path d="M0 124 C60 118, 75 94, 130 105 S190 72, 240 89 S310 94, 355 53 S430 74, 466 61 S535 78, 580 34 S645 51, 700 18" /><path className="fill" d="M0 124 C60 118, 75 94, 130 105 S190 72, 240 89 S310 94, 355 53 S430 74, 466 61 S535 78, 580 34 S645 51, 700 18 V150 H0Z" /></svg></div><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></article><article className="panel ai-card"><span className="ai-orbit">✦</span><span className="eyebrow">PlanAI assistant</span><h2>What&apos;s on your mind?</h2><p>Tell me what you want to accomplish and I&apos;ll help shape it into a plan.</p><button className="assistant-cta" onClick={onAssistant}>Start a conversation <span>↗</span></button></article></section><section className="lower-grid"><article className="panel"><div className="panel-heading"><h2>Today&apos;s tasks</h2><button className="text-button">View all →</button></div><div className="task-list">{tasks.slice(0, 3).map((task, index) => <TaskRow task={task} key={task.title} onComplete={() => onComplete(index)} />)}</div></article><article className="panel activity-panel"><div className="panel-heading"><h2>Recent activity</h2><button className="text-button">See all</button></div><Activity icon="✓" title="Task completed" detail="Review design system updates" time="2m ago" color="green" /><Activity icon="✦" title="AI created a plan" detail="Q3 product strategy" time="1h ago" color="violet" /><Activity icon="+" title="New task added" detail="Research onboarding patterns" time="3h ago" color="blue" /></article></section></>; }
function TasksView({ tasks, query, setQuery, onComplete, onNew }: { tasks: Task[]; query: string; setQuery: (value: string) => void; onComplete: (index: number) => void; onNew: () => void }) { return <><div className="view-toolbar"><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tasks..." /></div><button className="filter-button">☷ Filter</button><button className="filter-button">↕ Sort</button><button className="primary-button" onClick={onNew}>+ New task</button></div><div className="task-summary"><span>All tasks <b>{tasks.length}</b></span><span>To do <b>2</b></span><span>In progress <b>1</b></span><span>Completed <b>1</b></span></div><section className="full-panel panel"><div className="table-head"><span>Task</span><span>Status</span><span>Priority</span><span>Due date</span><span /></div>{tasks.map((task, index) => <div className="table-row" key={task.title}><div className="table-task"><button className={`check ${task.done ? "done" : ""}`} onClick={() => onComplete(index)}>{task.done ? "✓" : ""}</button><span className={`task-color ${task.color}`} /><div><strong>{task.title}</strong><small>{task.project}</small></div></div><span className={`pill ${task.status.toLowerCase().replace(" ", "-")}`}>{task.status}</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><span className="due-date">{task.date}</span><button className="row-menu">•••</button></div>)}</section></>; }
function Assistant({ prompt, setPrompt, thinking, ask }: { prompt: string; setPrompt: (value: string) => void; thinking: boolean; ask: () => void }) { const [messages, setMessages] = useState([{ from: "ai", text: "Hey Alex. What are we making space for today?" }]); const send = () => { if (!prompt.trim()) return; setMessages([...messages, { from: "user", text: prompt }]); ask(); setPrompt(""); }; return <div className="assistant-layout"><section className="panel chat-window"><div className="chat-header"><span className="ai-avatar">✦</span><div><strong>PlanAI assistant</strong><small><i /> Connected to Notion</small></div><button className="icon-button">•••</button></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.from}`} key={`${message.text}-${index}`}><span className="message-avatar">{message.from === "ai" ? "✦" : "AM"}</span><div>{message.text}</div></div>)}{thinking && <div className="message ai"><span className="message-avatar">✦</span><div className="typing"><i /><i /><i /></div></div>}</div><div className="chat-compose"><input value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder="Ask anything about your work..." /><button onClick={send} aria-label="Send message">↑</button></div></section><aside className="assistant-aside"><span className="eyebrow">Try asking</span><h3>Start with an idea</h3>{["Create a high priority task", "Show my tasks for today", "Plan my week", "What needs my attention?"].map((suggestion) => <button className="suggestion" key={suggestion} onClick={() => setPrompt(suggestion)}>{suggestion}<span>↗</span></button>)}</aside></div>; }
function Planner({ tasks }: { tasks: Task[] }) { const days = ["Mon 24", "Tue 25", "Wed 26", "Thu 27", "Fri 28", "Sat 29", "Sun 30"]; return <><div className="calendar-toolbar"><button className="icon-button">‹</button><h2>August 24 – 30, 2026</h2><button className="icon-button">›</button><button className="filter-button today">Today</button><button className="filter-button">Week ⌄</button></div><section className="calendar panel"><div className="calendar-head"><span />{days.map((day, index) => <span className={index === 0 ? "today-label" : ""} key={day}>{day}</span>)}</div><div className="calendar-body"><div className="time-labels">{["9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM"].map((time) => <span key={time}>{time}</span>)}</div><div className="calendar-columns">{days.map((day, index) => <div className="day-column" key={day}><div className="drop-zone" style={{ top: index === 0 ? "16%" : index === 3 ? "44%" : "70%" }}><span className={`task-color ${tasks[index % tasks.length].color}`} />{tasks[index % tasks.length].title}</div></div>)}</div></div></section><section className="upcoming panel"><div className="panel-heading"><h2>Upcoming deadlines</h2><span>Next 7 days</span></div><div className="deadline-list"><span>Today</span><strong>Finalize Q3 product strategy</strong><b>4:00 PM</b><span>Aug 27</span><strong>Research onboarding patterns</strong><b>All day</b></div></section></>; }
function Analytics() { return <><section className="stats-grid"><Stat label="Completion rate" value="76%" change="9%" positive /><Stat label="Focus hours" value="34.8h" change="12%" positive /><Stat label="Avg. task time" value="42m" change="6%" /><Stat label="Tasks completed" value="23" change="18%" positive /></section><section className="analytics-grid"><article className="panel large-chart"><div className="panel-heading"><div><span className="eyebrow">Momentum</span><h2>Productivity over time</h2></div><span>Last 30 days ⌄</span></div><div className="line-chart tall"><svg viewBox="0 0 700 190" preserveAspectRatio="none"><path d="M0 158 C75 135, 90 146, 150 125 S220 155, 280 112 S355 80, 400 105 S465 67, 515 80 S600 30, 700 45" /><path className="fill" d="M0 158 C75 135, 90 146, 150 125 S220 155, 280 112 S355 80, 400 105 S465 67, 515 80 S600 30, 700 45 V190 H0Z" /></svg></div></article><article className="panel distribution"><div className="panel-heading"><h2>Priority distribution</h2><span>48 tasks</span></div><div className="donut"><div><strong>48</strong><small>total tasks</small></div></div><div className="legend"><span><i className="coral-bg" />High <b>12</b></span><span><i className="yellow-bg" />Medium <b>24</b></span><span><i className="blue-bg" />Low <b>12</b></span></div></article></section><section className="panel"><div className="panel-heading"><h2>Weekly progress</h2><span>Goal: 30 tasks</span></div><div className="weekly-bars">{[["Mon", 60], ["Tue", 78], ["Wed", 44], ["Thu", 92], ["Fri", 68], ["Sat", 35], ["Sun", 55]].map(([day, height]) => <div key={day as string}><span style={{ height: `${height}%` }} /><small>{day}</small></div>)}</div></section></>; }
function Settings() { return <div className="settings-grid"><section className="panel settings-card"><div className="settings-title"><span className="avatar large">AM</span><div><h2>Alex Morgan</h2><p>alex.morgan@example.com</p></div><button className="filter-button">Edit profile</button></div><div className="setting-row"><div><strong>Appearance</strong><small>Choose how PlanAI looks for you</small></div><div className="segmented"><button className="selected">Dark</button><button>Light</button><button>System</button></div></div><div className="setting-row"><div><strong>Reduce motion</strong><small>Use fewer animations throughout the app</small></div><button className="toggle"><i /></button></div></section><section className="panel settings-card"><div className="panel-heading"><div><span className="eyebrow">Connections</span><h2>Integrations</h2></div></div><div className="connection"><span className="connection-icon notion">N</span><div><strong>Notion</strong><small>Tasks are synced with your workspace</small></div><span className="connected">Connected</span></div><div className="connection"><span className="connection-icon sparkle">✦</span><div><strong>AI provider</strong><small>Ready to plan alongside you</small></div><span className="connected">Connected</span></div></section></div>; }
function NewTaskModal({ onClose }: { onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(event) => event.stopPropagation()}><span className="eyebrow">Quick capture</span><h2>Create a new task</h2><p>Give your next action a clear home.</p><input autoFocus placeholder="What needs to be done?" /><div className="modal-fields"><button>Priority <span>High ⌄</span></button><button>Due date <span>Today ⌄</span></button></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={onClose}>Create task</button></div></div></div>; }
